#!/command/with-contenv bash

bootstrap_filesystem() {
    if [ ! -d "${CONFIG_PATH}" ]; then
        mkdir -p "${CONFIG_PATH}"
    fi

    if [ $(stat -c %U "${CONFIG_PATH}") != "${UNIT_USER}" ] ; then chown "${UNIT_USER}":"${UNIT_GROUP}" "${CONFIG_PATH}" ; fi
    ln -sf "${CONFIG_PATH}"/"${CONFIG_FILE}" "${UNIT_WEBROOT}"/config.json
}

generate_configuration() {
    if [ "${SETUP_MODE,,}" = "auto" ] ; then
        print_debug "Automatically generating configuration based on environment variables and defaults"

        if  [ ! -f "${CONFIG_PATH}"/"${CONFIG_FILE}" ] ; then
            cat <<EOF | silent sudo -u "${UNIT_USER}" tee "${CONFIG_PATH}"/"${CONFIG_FILE}"
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix-client.matrix.org",
            "server_name": "matrix.org"
        },
        "m.identity_server": {
            "base_url": "https://vector.im"
        }
    },
    "disable_custom_urls": false,
    "disable_guests": false,
    "disable_login_language_selector": false,
    "disable_3pid_login": false,
    "brand": "Element",
    "integrations_ui_url": "https://scalar.vector.im/",
    "integrations_rest_url": "https://scalar.vector.im/api",
    "integrations_widgets_urls": [
        "https://scalar.vector.im/_matrix/integrations/v1",
        "https://scalar.vector.im/api",
        "https://scalar-staging.vector.im/_matrix/integrations/v1",
        "https://scalar-staging.vector.im/api",
        "https://scalar-staging.riot.im/scalar/api"
    ],
    "bug_report_endpoint_url": "https://element.io/bugreports/submit",
    "uisi_autorageshake_app": "element-auto-uisi",
    "default_country_code": "US",
    "show_labs_settings": false,
    "features": { },
    "default_federate": true,
    "default_theme": "light",
    "room_directory": {
        "servers": [
            "matrix.org"
        ]
    },
    "enable_presence_by_hs_url": {
        "https://matrix.org": false,
        "https://matrix-client.matrix.org": false
    },
    "setting_defaults": {
        "breadcrumbs": true,
         "MessageComposerInput.showStickersButton": false,
         "MessageComposerInput.showPollsButton": false
    },
    "jitsi": {
        "preferred_domain": "meet.element.io"
    },
    "jitsi_widget": {
      "skip_built_in_welcome_screen": true
    },
    "voip": {
      "obey_asserted_identity": false
    },
    "element_call": {
        "url": "https://call.element.io",
        "participant_limit": 8,
        "brand": "Element Call",
        "exclusive": false,
    },

    logout_redirect_url: null,
    "sso_redirect_options": {
      "immediate": false,
      "on_welcome_page": true,
    },

    "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
}
EOF
        fi

        ## Home Server + Identity Settings
        yq -i '."default_server_config"."m.homeserver"."base_url" = "'"$(echo "${HOME_SERVER_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json

        if [ -z "${HOME_SERVER_NAME}" ]; then
            HOME_SERVER_NAME=$(echo "${HOME_SERVER_URL}" | rev | cut -d . -f1,2 | rev)
        fi

        yq -i '."default_server_config"."m.homeserver"."server_name" = "'"$(echo "${HOME_SERVER_NAME}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."default_server_config"."m.identity_server"."base_url" = "'"$(echo "${IDENTITY_SERVER_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json

        ## Integrations
        yq -i '."integrations_ui_url" = "'"$(echo "${INTEGRATIONS_UI_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."integrations_rest_url" = "'"$(echo "${INTEGRATIONS_UI_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        #yq -i '."integrations_widgets_url" # Multi Value

        ## Server Settings
        yq -i '."bug_report_endpoint_url" = "'"$(echo "${BUG_REPORT_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."brand" = "'"$(echo "${BRAND}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."default_federate" = '"$(echo "${DEFAULT_ROOM_FEDERATE,,}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        if var_true "${ENABLE_CUSTOM_HOME_SERVER_URL}" ; then ENABLE_CUSTOM_HOME_SERVER_URL=false ; else ENABLE_CUSTOM_HOME_SERVER_URL=true ; fi
        yq -i '."disable_custom_urls" = '"$(echo ${ENABLE_CUSTOM_HOME_SERVER_URL,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        if var_true "${ENABLE_GUESTS}" ; then ENABLE_GUESTS=false ; else ENABLE_GUESTS=true ; fi
        yq -i '."disable_guests" = '"$(echo ${ENABLE_GUESTS,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        if var_true "${ENABLE_LOGIN_LANGUAGE_SELECTION}" ; then ENABLE_LOGIN_LANGUAGE_SELECTION=false ; else ENABLE_LOGIN_LANGUAGE_SELECTION=true ; fi
        yq -i '."disable_login_language_selector" = '"$(echo ${ENABLE_LOGIN_LANGUAGE_SELECTION,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        if var_true "${ENABLE_3PID_LOGIN}" ; then ENABLE_3PID_LOGIN=false ; else ENABLE_3PID_LOGIN=true ; fi
        yq -i '."disable_3pid_login" = '"$(echo "${ENABLE_3PID_LOGIN,,}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."show_labs_settings" = '"$(echo ${SETTINGS_SHOW_LABS,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json

        ### SSO
        yq -i '."logout_redirect_url" = "'"$(echo "${LOGOUT_REDIRECT_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."sso_redirect_options"."immediate" = '"$(echo "${SSO_AUTO_LOGIN,,}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json

        ## Default Setings (User)
        yq -i '."default_country_code" = "'"$(echo "${DEFAULT_COUNTRY_CODE}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."default_theme" = "'"$(echo "${DEFAULT_THEME}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."breadcrumbs" = '"$(echo "${DEFAULT_ENABLE_BREADCRUMBS,,}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."MessageComposerInput.showPollsButton" = '"$(echo ${DEFAULT_SHOW_POLLS_BUTTON,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."MessageComposerInput.showStickersButton" = '"$(echo ${DEFAULT_SHOW_STICKERS_BUTTON,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."FTUE.userOnboardingButton" = '"$(echo ${DEFAULT_SHOW_WELCOME_CHECKLIST,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.urlPreviews" = '"$(echo ${ENABLE_URL_PREVIEW,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.feedback" = '"$(echo ${ENABLE_FEEDBACK,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.voip" = '"$(echo ${ENABLE_VOIP,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.widgets" = '"$(echo ${ENABLE_WIDGETS,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.advancedSettings" = '"$(echo ${ENABLE_ADVANCED_SETTINGS,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.shareQrCode" = '"$(echo ${ENABLE_SHARE_QR,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.shareSocial" = '"$(echo ${ENABLE_SHARE_SOCIAL,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.identityServer" = '"$(echo ${ENABLE_IDENTITY_SERVICES,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.identityServer" = '"$(echo ${ENABLE_IDENTITY_SERVICES,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.thirdPartyIdidentityServer" = '"$(echo ${ENABLE_3PID_SERVICES,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.identityServer" = '"$(echo ${ENABLE_IDENTITY_SERVICES,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.registration" = '"$(echo ${ENABLE_REGISTRATION,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.passwordReset" = '"$(echo ${ENABLE_PASSWORD_RESET,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.deactivate" = '"$(echo ${ENABLE_DEACTIVATE_ACCOUNT,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.advancedEncryption" = '"$(echo ${ENABLE_ADVANCED_ENCRYPTION,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.roomHistorySettings" = '"$(echo ${ENABLE_ROOM_HISTORY_SETTINGS,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.TimelineEnableRelativeDates" = '"$(echo ${ENABLE_RELATIVE_DATES,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."setting_defaults"."UIFeature.BulkUnverifiedSessionsReminder" = '"$(echo ${ENABLE_UNVERIFIED_SESSION_REMINDER,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json

        ## VoIP
        yq -i '."element_call"."brand" = "'"$(echo "${CALL_BRAND}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."element_call"."exclusive" = '"$(echo "${CALL_EXCLUSIVE,,}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."element_call"."participant_limit" = '"$(echo "${CALL_USER_LIMIT}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."element_call"."url" = "'"$(echo "${CALL_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."jitsi"."preferred_domain" = "'"$(echo "${JITSI_DOMAIN}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."jitsi_widget"."skip_built_in_welcome_screen" = '"$(echo "${JITSI_SKIP_WELCOME_SCREEN,,}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
        yq -i '."voip"."obey_asserted_identity" = '"$(echo "${VOIP_OBEY_ASSERTED_IDENTITY,,}")"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json

        ## Maps
        yq -i '."map_style_url" = "'"$(echo "${MAP_STYLE_URL}")"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json

        #yq -i '."s" = "'"$(echo ${VAR_QUOTES})"'"' "${CONFIG_PATH}"/"${CONFIG_FILE}"
        #yq -i '."s" = '"$(echo ${VAR_NOQUOTES,,})"'' "${CONFIG_PATH}"/"${CONFIG_FILE}" -o json
    else
        print_debug "Manual mode detected - Using '${CONFIG_PATH}/${CONFIG_FILE}' for configuration"
    fi
}
